### ISSUE TITLE
LICENSE: Consider adding a classpath exception / switching to LGPL

### ISSUE THREAD

**Issue by richardTowers** [litsec/eidas-opensaml#2]
For eIDAS implementors that are releasing their code under non-GPL licenses or building proprietary implementations it would be beneficial to have the code licensed more permissively.

On the other hand I completely acknowledge the Free Software arguments about releasing libraries under the full GPL ([Why you shouldn't use the Lesser GPL for your next library](https://www.gnu.org/licenses/why-not-lgpl.html)).

Would the copyright holders consider modifying the license to include a [linking exception](https://en.wikipedia.org/wiki/GPL_linking_exception) or switching to the LGPL (or another more permissive license)?

**Comment by martin-lindstrom** [comment]
Short answer. Yes, we'll be glad to switch to LGPL to enable a wider use of the library.

**Comment by martin-lindstrom** [comment]
In fact. We'll change to Apache License 2.0, which makes a lot more sense since OpenSAML uses Apache License. Will hopefully be done during the coming week.

**Comment by martin-lindstrom** [comment]
Version 1.0.5 now used Apache 2.0 license.
